// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLOHzPHfYOnodhlmuLQv17YF905KXrojg',
    appId: '1:229209086436:android:5176b148d22482b5f8cff1',
    messagingSenderId: '229209086436',
    projectId: 'magicalvibe-e3e86',
    storageBucket: 'magicalvibe-e3e86.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbJ2P_RKPsfFy9Mneny-oWps7jlZsMlU0',
    appId: '1:229209086436:web:c58a4e7ac399f922f8cff1',
    messagingSenderId: '229209086436',
    projectId: 'magicalvibe-e3e86',
    authDomain: 'magicalvibe-e3e86.firebaseapp.com',
    storageBucket: 'magicalvibe-e3e86.firebasestorage.app',
    measurementId: 'G-V5MGXX4Y20',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJ2P_RKPsfFy9Mneny-oWps7jlZsMlU0',
    appId: '1:229209086436:web:c58a4e7ac399f922f8cff1',
    messagingSenderId: '229209086436',
    projectId: 'magicalvibe-e3e86',
    authDomain: 'magicalvibe-e3e86.firebaseapp.com',
    storageBucket: 'magicalvibe-e3e86.firebasestorage.app',
    measurementId: 'G-V5MGXX4Y20',
  );

}